import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from '@/components/providers';
import Script from 'next/script';
import Navbar from '@/components/navbar';
import { Client } from '@notionhq/client';

// Initialize Notion client
const notion = new Client({ auth: process.env.NOTION_API_KEY });
const databaseId = process.env.NOTION_DATABASE_ID ?? '';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FinanClub",
  description: "Generated by create next app",
};

// Function to fetch categories from Notion
async function fetchCategories() {
  try {
    const database = await notion.databases.retrieve({ database_id: databaseId });
    const categoryProperty = database.properties.Category;

    if (categoryProperty.type === 'select') {
      return categoryProperty.select.options;
    }
    
    return [];
  } catch (error) {
    console.error('Error fetching categories from Notion:', error);
    return [];
  }
}

// Main layout component
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch categories
  const categories = await fetchCategories();

  return (
    <>
      <html>
      {process.env.ADSENSE_P_ID &&
        <head>
          <Script
            async
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-${process.env.ADSENSE_P_ID}`}
            crossOrigin='anonymous'
            strategy='afterInteractive'
          />
        </head>}
        <body>
          <Providers
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar categories={categories} />
            <div className='mx-auto max-w-2xl'>
            {children}
            </div>
          </Providers>
        </body>
      </html>
    </>
  );
}
